/* automatically generated by rust-bindgen 0.72.1 */

pub const _LIBCPP_ABI_VERSION: u32 = 1;
pub const _LIBCPP_ABI_FORCE_ITANIUM: u32 = 0;
pub const _LIBCPP_ABI_FORCE_MICROSOFT: u32 = 0;
pub const _LIBCPP_HAS_THREADS: u32 = 1;
pub const _LIBCPP_HAS_MONOTONIC_CLOCK: u32 = 1;
pub const _LIBCPP_HAS_TERMINAL: u32 = 1;
pub const _LIBCPP_HAS_MUSL_LIBC: u32 = 0;
pub const _LIBCPP_HAS_THREAD_API_PTHREAD: u32 = 0;
pub const _LIBCPP_HAS_THREAD_API_EXTERNAL: u32 = 0;
pub const _LIBCPP_HAS_THREAD_API_WIN32: u32 = 0;
pub const _LIBCPP_HAS_THREAD_API_C11: u32 = 0;
pub const _LIBCPP_HAS_VENDOR_AVAILABILITY_ANNOTATIONS: u32 = 1;
pub const _LIBCPP_HAS_FILESYSTEM: u32 = 1;
pub const _LIBCPP_HAS_RANDOM_DEVICE: u32 = 1;
pub const _LIBCPP_HAS_LOCALIZATION: u32 = 1;
pub const _LIBCPP_HAS_UNICODE: u32 = 1;
pub const _LIBCPP_HAS_WIDE_CHARACTERS: u32 = 1;
pub const _LIBCPP_HAS_TIME_ZONE_DATABASE: u32 = 0;
pub const _LIBCPP_INSTRUMENTED_WITH_ASAN: u32 = 0;
pub const _LIBCPP_HARDENING_MODE_DEFAULT: u32 = 2;
pub const _LIBCPP_OBJECT_FORMAT_MACHO: u32 = 1;
pub const _LIBCPP_STD_VER: u32 = 14;
pub const _LIBCPP_HAS_RTTI: u32 = 1;
pub const _LIBCPP_HAS_EXCEPTIONS: u32 = 1;
pub const _LIBCPP_INTRODUCED_IN_LLVM_20: u32 = 1;
pub const _LIBCPP_INTRODUCED_IN_LLVM_19: u32 = 1;
pub const _LIBCPP_INTRODUCED_IN_LLVM_18: u32 = 1;
pub const _LIBCPP_INTRODUCED_IN_LLVM_16: u32 = 1;
pub const _LIBCPP_INTRODUCED_IN_LLVM_15: u32 = 1;
pub const _LIBCPP_INTRODUCED_IN_LLVM_14: u32 = 1;
pub const _LIBCPP_INTRODUCED_IN_LLVM_12: u32 = 1;
pub const _LIBCPP_INTRODUCED_IN_LLVM_11: u32 = 1;
pub const _LIBCPP_INTRODUCED_IN_LLVM_9: u32 = 1;
pub const _LIBCPP_INTRODUCED_IN_LLVM_4: u32 = 1;
pub const _LIBCPP_AVAILABILITY_HAS_BAD_OPTIONAL_ACCESS: u32 = 1;
pub const _LIBCPP_AVAILABILITY_HAS_BAD_VARIANT_ACCESS: u32 = 1;
pub const _LIBCPP_AVAILABILITY_HAS_BAD_ANY_CAST: u32 = 1;
pub const _LIBCPP_AVAILABILITY_HAS_FILESYSTEM_LIBRARY: u32 = 1;
pub const _LIBCPP_AVAILABILITY_HAS_SYNC: u32 = 1;
pub const _LIBCPP_AVAILABILITY_HAS_ADDITIONAL_IOSTREAM_EXPLICIT_INSTANTIATIONS_1: u32 = 1;
pub const _LIBCPP_AVAILABILITY_HAS_TO_CHARS_FLOATING_POINT: u32 = 1;
pub const _LIBCPP_AVAILABILITY_HAS_VERBOSE_ABORT: u32 = 1;
pub const _LIBCPP_AVAILABILITY_HAS_PMR: u32 = 1;
pub const _LIBCPP_AVAILABILITY_HAS_INIT_PRIMARY_EXCEPTION: u32 = 1;
pub const _LIBCPP_AVAILABILITY_HAS_PRINT: u32 = 1;
pub const _LIBCPP_AVAILABILITY_HAS_TZDB: u32 = 1;
pub const _LIBCPP_AVAILABILITY_HAS_BAD_FUNCTION_CALL_KEY_FUNCTION: u32 = 1;
pub const _LIBCPP_AVAILABILITY_HAS_BAD_EXPECTED_ACCESS_KEY_FUNCTION: u32 = 1;
pub const _LIBCPP_AVAILABILITY_HAS_FROM_CHARS_FLOATING_POINT: u32 = 1;
pub const _LIBCPP_VERSION: u32 = 200100;
pub const _LIBCPP_HARDENING_MODE_NONE: u32 = 2;
pub const _LIBCPP_HARDENING_MODE_FAST: u32 = 4;
pub const _LIBCPP_HARDENING_MODE_EXTENSIVE: u32 = 16;
pub const _LIBCPP_HARDENING_MODE_DEBUG: u32 = 8;
pub const _LIBCPP_HARDENING_MODE: u32 = 2;
pub const _LIBCPP_HAS_EXPERIMENTAL_LIBRARY: u32 = 0;
pub const _LIBCPP_HAS_EXPERIMENTAL_PSTL: u32 = 0;
pub const _LIBCPP_HAS_EXPERIMENTAL_TZDB: u32 = 0;
pub const _LIBCPP_HAS_EXPERIMENTAL_SYNCSTREAM: u32 = 0;
pub const _LIBCPP_HAS_OPEN_WITH_WCHAR: u32 = 0;
pub const _LIBCPP_HAS_BITSCAN64: u32 = 0;
pub const _LIBCPP_HAS_OBJC_ARC: u32 = 0;
pub const _LIBCPP_HAS_OBJC_ARC_WEAK: u32 = 0;
pub const _LIBCPP_HAS_EXTENSION_BLOCKS: u32 = 1;
pub const _LIBCPP_HAS_BLOCKS_RUNTIME: u32 = 1;
pub const _LIBCPP_HAS_ASAN: u32 = 0;
pub const _LIBCPP_HAS_INT128: u32 = 1;
pub const _LIBCPP_LOCALE__L_EXTENSIONS: u32 = 1;
pub const _LIBCPP_HAS_LIBRARY_ALIGNED_ALLOCATION: u32 = 1;
pub const _LIBCPP_HAS_ALIGNED_ALLOCATION: u32 = 0;
pub const _LIBCPP_HAS_C11_ALIGNED_ALLOC: u32 = 1;
pub const _LIBCPP_HAS_CHAR8_T: u32 = 0;
pub const _LIBCPP_HAS_COND_CLOCKWAIT: u32 = 0;
pub const _LIBCPP_HAS_TRIVIAL_MUTEX_DESTRUCTION: u32 = 0;
pub const _LIBCPP_HAS_TRIVIAL_CONDVAR_DESTRUCTION: u32 = 0;
pub const _LIBCPP_HAS_C_ATOMIC_IMP: u32 = 1;
pub const _LIBCPP_HAS_GCC_ATOMIC_IMP: u32 = 0;
pub const _LIBCPP_HAS_EXTERNAL_ATOMIC_IMP: u32 = 0;
pub const _LIBCPP_HAS_ATOMIC_HEADER: u32 = 1;
pub const _LIBCPP_HAS_THREAD_SAFETY_ANNOTATIONS: u32 = 0;
pub const _LIBCPP_HAS_C8RTOMB_MBRTOC8: u32 = 0;
pub const _LIBCPP_HAS_EXPLICIT_THIS_PARAMETER: u32 = 0;
pub const __WORDSIZE: u32 = 64;
pub const __has_safe_buffers: u32 = 1;
pub const __DARWIN_ONLY_64_BIT_INO_T: u32 = 1;
pub const __DARWIN_ONLY_UNIX_CONFORMANCE: u32 = 1;
pub const __DARWIN_ONLY_VERS_1050: u32 = 1;
pub const __DARWIN_UNIX03: u32 = 1;
pub const __DARWIN_64_BIT_INO_T: u32 = 1;
pub const __DARWIN_VERS_1050: u32 = 1;
pub const __DARWIN_NON_CANCELABLE: u32 = 0;
pub const __DARWIN_SUF_EXTSN: &[u8; 14] = b"$DARWIN_EXTSN\0";
pub const __DARWIN_C_ANSI: u32 = 4096;
pub const __DARWIN_C_FULL: u32 = 900000;
pub const __DARWIN_C_LEVEL: u32 = 900000;
pub const __DARWIN_NO_LONG_LONG: u32 = 0;
pub const _DARWIN_FEATURE_64_BIT_INODE: u32 = 1;
pub const _DARWIN_FEATURE_ONLY_64_BIT_INODE: u32 = 1;
pub const _DARWIN_FEATURE_ONLY_VERS_1050: u32 = 1;
pub const _DARWIN_FEATURE_ONLY_UNIX_CONFORMANCE: u32 = 1;
pub const _DARWIN_FEATURE_UNIX_CONFORMANCE: u32 = 3;
pub const __has_ptrcheck: u32 = 0;
pub const __has_bounds_safety_attributes: u32 = 0;
pub const USE_CLANG_TYPES: u32 = 0;
pub const __PTHREAD_SIZE__: u32 = 8176;
pub const __PTHREAD_ATTR_SIZE__: u32 = 56;
pub const __PTHREAD_MUTEXATTR_SIZE__: u32 = 8;
pub const __PTHREAD_MUTEX_SIZE__: u32 = 56;
pub const __PTHREAD_CONDATTR_SIZE__: u32 = 8;
pub const __PTHREAD_COND_SIZE__: u32 = 40;
pub const __PTHREAD_ONCE_SIZE__: u32 = 8;
pub const __PTHREAD_RWLOCK_SIZE__: u32 = 192;
pub const __PTHREAD_RWLOCKATTR_SIZE__: u32 = 16;
pub const INT8_MAX: u32 = 127;
pub const INT16_MAX: u32 = 32767;
pub const INT32_MAX: u32 = 2147483647;
pub const INT64_MAX: u64 = 9223372036854775807;
pub const INT8_MIN: i32 = -128;
pub const INT16_MIN: i32 = -32768;
pub const INT32_MIN: i32 = -2147483648;
pub const INT64_MIN: i64 = -9223372036854775808;
pub const UINT8_MAX: u32 = 255;
pub const UINT16_MAX: u32 = 65535;
pub const UINT32_MAX: u32 = 4294967295;
pub const UINT64_MAX: i32 = -1;
pub const INT_LEAST8_MIN: i32 = -128;
pub const INT_LEAST16_MIN: i32 = -32768;
pub const INT_LEAST32_MIN: i32 = -2147483648;
pub const INT_LEAST64_MIN: i64 = -9223372036854775808;
pub const INT_LEAST8_MAX: u32 = 127;
pub const INT_LEAST16_MAX: u32 = 32767;
pub const INT_LEAST32_MAX: u32 = 2147483647;
pub const INT_LEAST64_MAX: u64 = 9223372036854775807;
pub const UINT_LEAST8_MAX: u32 = 255;
pub const UINT_LEAST16_MAX: u32 = 65535;
pub const UINT_LEAST32_MAX: u32 = 4294967295;
pub const UINT_LEAST64_MAX: i32 = -1;
pub const INT_FAST8_MIN: i32 = -128;
pub const INT_FAST16_MIN: i32 = -32768;
pub const INT_FAST32_MIN: i32 = -2147483648;
pub const INT_FAST64_MIN: i64 = -9223372036854775808;
pub const INT_FAST8_MAX: u32 = 127;
pub const INT_FAST16_MAX: u32 = 32767;
pub const INT_FAST32_MAX: u32 = 2147483647;
pub const INT_FAST64_MAX: u64 = 9223372036854775807;
pub const UINT_FAST8_MAX: u32 = 255;
pub const UINT_FAST16_MAX: u32 = 65535;
pub const UINT_FAST32_MAX: u32 = 4294967295;
pub const UINT_FAST64_MAX: i32 = -1;
pub const INTPTR_MAX: u64 = 9223372036854775807;
pub const INTPTR_MIN: i64 = -9223372036854775808;
pub const UINTPTR_MAX: i32 = -1;
pub const SIZE_MAX: i32 = -1;
pub const WINT_MIN: i32 = -2147483648;
pub const WINT_MAX: u32 = 2147483647;
pub const SIG_ATOMIC_MIN: i32 = -2147483648;
pub const SIG_ATOMIC_MAX: u32 = 2147483647;
pub const __cpp_lib_chrono_udls: u32 = 201304;
pub const __cpp_lib_complex_udls: u32 = 201309;
pub const __cpp_lib_exchange_function: u32 = 201304;
pub const __cpp_lib_generic_associative_lookup: u32 = 201304;
pub const __cpp_lib_integer_sequence: u32 = 201304;
pub const __cpp_lib_integral_constant_callable: u32 = 201304;
pub const __cpp_lib_is_final: u32 = 201402;
pub const __cpp_lib_is_null_pointer: u32 = 201309;
pub const __cpp_lib_make_reverse_iterator: u32 = 201402;
pub const __cpp_lib_make_unique: u32 = 201304;
pub const __cpp_lib_null_iterators: u32 = 201304;
pub const __cpp_lib_quoted_string_io: u32 = 201304;
pub const __cpp_lib_result_of_sfinae: u32 = 201210;
pub const __cpp_lib_robust_nonmodifying_seq_ops: u32 = 201304;
pub const __cpp_lib_shared_timed_mutex: u32 = 201402;
pub const __cpp_lib_string_udls: u32 = 201304;
pub const __cpp_lib_transformation_trait_aliases: u32 = 201304;
pub const __cpp_lib_transparent_operators: u32 = 201210;
pub const __cpp_lib_tuple_element_t: u32 = 201402;
pub const __cpp_lib_tuples_by_type: u32 = 201304;
pub const NRD_VERSION_MAJOR: u32 = 4;
pub const NRD_VERSION_MINOR: u32 = 17;
pub const NRD_VERSION_BUILD: u32 = 2;
pub const NRD_VERSION_DATE: &[u8; 14] = b"17 March 2026\0";
pub const NRD_DESCS_VERSION_MAJOR: u32 = 4;
pub const NRD_DESCS_VERSION_MINOR: u32 = 17;
pub const NRD_SETTINGS_VERSION_MAJOR: u32 = 4;
pub const NRD_SETTINGS_VERSION_MINOR: u32 = 17;
pub type int_least8_t = i8;
pub type int_least16_t = i16;
pub type int_least32_t = i32;
pub type int_least64_t = i64;
pub type uint_least8_t = u8;
pub type uint_least16_t = u16;
pub type uint_least32_t = u32;
pub type uint_least64_t = u64;
pub type int_fast8_t = i8;
pub type int_fast16_t = i16;
pub type int_fast32_t = i32;
pub type int_fast64_t = i64;
pub type uint_fast8_t = u8;
pub type uint_fast16_t = u16;
pub type uint_fast32_t = u32;
pub type uint_fast64_t = u64;
pub type __int8_t = ::std::os::raw::c_schar;
pub type __uint8_t = ::std::os::raw::c_uchar;
pub type __int16_t = ::std::os::raw::c_short;
pub type __uint16_t = ::std::os::raw::c_ushort;
pub type __int32_t = ::std::os::raw::c_int;
pub type __uint32_t = ::std::os::raw::c_uint;
pub type __int64_t = ::std::os::raw::c_longlong;
pub type __uint64_t = ::std::os::raw::c_ulonglong;
pub type __darwin_intptr_t = ::std::os::raw::c_long;
pub type __darwin_natural_t = ::std::os::raw::c_uint;
pub type __darwin_ct_rune_t = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Copy, Clone)]
pub union __mbstate_t {
    pub __mbstate8: [::std::os::raw::c_char; 128usize],
    pub _mbstateL: ::std::os::raw::c_longlong,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of __mbstate_t"][::std::mem::size_of::<__mbstate_t>() - 128usize];
    ["Alignment of __mbstate_t"][::std::mem::align_of::<__mbstate_t>() - 8usize];
    ["Offset of field: __mbstate_t::__mbstate8"]
        [::std::mem::offset_of!(__mbstate_t, __mbstate8) - 0usize];
    ["Offset of field: __mbstate_t::_mbstateL"]
        [::std::mem::offset_of!(__mbstate_t, _mbstateL) - 0usize];
};
pub type __darwin_mbstate_t = __mbstate_t;
pub type __darwin_ptrdiff_t = ::std::os::raw::c_long;
pub type __darwin_size_t = ::std::os::raw::c_ulong;
pub type __darwin_va_list = __builtin_va_list;
pub type __darwin_wchar_t = ::std::os::raw::c_int;
pub type __darwin_rune_t = __darwin_wchar_t;
pub type __darwin_wint_t = ::std::os::raw::c_int;
pub type __darwin_clock_t = ::std::os::raw::c_ulong;
pub type __darwin_socklen_t = __uint32_t;
pub type __darwin_ssize_t = ::std::os::raw::c_long;
pub type __darwin_time_t = ::std::os::raw::c_long;
pub type __darwin_blkcnt_t = __int64_t;
pub type __darwin_blksize_t = __int32_t;
pub type __darwin_dev_t = __int32_t;
pub type __darwin_fsblkcnt_t = ::std::os::raw::c_uint;
pub type __darwin_fsfilcnt_t = ::std::os::raw::c_uint;
pub type __darwin_gid_t = __uint32_t;
pub type __darwin_id_t = __uint32_t;
pub type __darwin_ino64_t = __uint64_t;
pub type __darwin_ino_t = __darwin_ino64_t;
pub type __darwin_mach_port_name_t = __darwin_natural_t;
pub type __darwin_mach_port_t = __darwin_mach_port_name_t;
pub type __darwin_mode_t = __uint16_t;
pub type __darwin_off_t = __int64_t;
pub type __darwin_pid_t = __int32_t;
pub type __darwin_sigset_t = __uint32_t;
pub type __darwin_suseconds_t = __int32_t;
pub type __darwin_uid_t = __uint32_t;
pub type __darwin_useconds_t = __uint32_t;
pub type __darwin_uuid_t = [::std::os::raw::c_uchar; 16usize];
pub type __darwin_uuid_string_t = [::std::os::raw::c_char; 37usize];
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __darwin_pthread_handler_rec {
    pub __routine: ::std::option::Option<unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void)>,
    pub __arg: *mut ::std::os::raw::c_void,
    pub __next: *mut __darwin_pthread_handler_rec,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of __darwin_pthread_handler_rec"]
        [::std::mem::size_of::<__darwin_pthread_handler_rec>() - 24usize];
    ["Alignment of __darwin_pthread_handler_rec"]
        [::std::mem::align_of::<__darwin_pthread_handler_rec>() - 8usize];
    ["Offset of field: __darwin_pthread_handler_rec::__routine"]
        [::std::mem::offset_of!(__darwin_pthread_handler_rec, __routine) - 0usize];
    ["Offset of field: __darwin_pthread_handler_rec::__arg"]
        [::std::mem::offset_of!(__darwin_pthread_handler_rec, __arg) - 8usize];
    ["Offset of field: __darwin_pthread_handler_rec::__next"]
        [::std::mem::offset_of!(__darwin_pthread_handler_rec, __next) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _opaque_pthread_attr_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 56usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _opaque_pthread_attr_t"][::std::mem::size_of::<_opaque_pthread_attr_t>() - 64usize];
    ["Alignment of _opaque_pthread_attr_t"]
        [::std::mem::align_of::<_opaque_pthread_attr_t>() - 8usize];
    ["Offset of field: _opaque_pthread_attr_t::__sig"]
        [::std::mem::offset_of!(_opaque_pthread_attr_t, __sig) - 0usize];
    ["Offset of field: _opaque_pthread_attr_t::__opaque"]
        [::std::mem::offset_of!(_opaque_pthread_attr_t, __opaque) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _opaque_pthread_cond_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 40usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _opaque_pthread_cond_t"][::std::mem::size_of::<_opaque_pthread_cond_t>() - 48usize];
    ["Alignment of _opaque_pthread_cond_t"]
        [::std::mem::align_of::<_opaque_pthread_cond_t>() - 8usize];
    ["Offset of field: _opaque_pthread_cond_t::__sig"]
        [::std::mem::offset_of!(_opaque_pthread_cond_t, __sig) - 0usize];
    ["Offset of field: _opaque_pthread_cond_t::__opaque"]
        [::std::mem::offset_of!(_opaque_pthread_cond_t, __opaque) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _opaque_pthread_condattr_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 8usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _opaque_pthread_condattr_t"]
        [::std::mem::size_of::<_opaque_pthread_condattr_t>() - 16usize];
    ["Alignment of _opaque_pthread_condattr_t"]
        [::std::mem::align_of::<_opaque_pthread_condattr_t>() - 8usize];
    ["Offset of field: _opaque_pthread_condattr_t::__sig"]
        [::std::mem::offset_of!(_opaque_pthread_condattr_t, __sig) - 0usize];
    ["Offset of field: _opaque_pthread_condattr_t::__opaque"]
        [::std::mem::offset_of!(_opaque_pthread_condattr_t, __opaque) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _opaque_pthread_mutex_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 56usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _opaque_pthread_mutex_t"][::std::mem::size_of::<_opaque_pthread_mutex_t>() - 64usize];
    ["Alignment of _opaque_pthread_mutex_t"]
        [::std::mem::align_of::<_opaque_pthread_mutex_t>() - 8usize];
    ["Offset of field: _opaque_pthread_mutex_t::__sig"]
        [::std::mem::offset_of!(_opaque_pthread_mutex_t, __sig) - 0usize];
    ["Offset of field: _opaque_pthread_mutex_t::__opaque"]
        [::std::mem::offset_of!(_opaque_pthread_mutex_t, __opaque) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _opaque_pthread_mutexattr_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 8usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _opaque_pthread_mutexattr_t"]
        [::std::mem::size_of::<_opaque_pthread_mutexattr_t>() - 16usize];
    ["Alignment of _opaque_pthread_mutexattr_t"]
        [::std::mem::align_of::<_opaque_pthread_mutexattr_t>() - 8usize];
    ["Offset of field: _opaque_pthread_mutexattr_t::__sig"]
        [::std::mem::offset_of!(_opaque_pthread_mutexattr_t, __sig) - 0usize];
    ["Offset of field: _opaque_pthread_mutexattr_t::__opaque"]
        [::std::mem::offset_of!(_opaque_pthread_mutexattr_t, __opaque) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _opaque_pthread_once_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 8usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _opaque_pthread_once_t"][::std::mem::size_of::<_opaque_pthread_once_t>() - 16usize];
    ["Alignment of _opaque_pthread_once_t"]
        [::std::mem::align_of::<_opaque_pthread_once_t>() - 8usize];
    ["Offset of field: _opaque_pthread_once_t::__sig"]
        [::std::mem::offset_of!(_opaque_pthread_once_t, __sig) - 0usize];
    ["Offset of field: _opaque_pthread_once_t::__opaque"]
        [::std::mem::offset_of!(_opaque_pthread_once_t, __opaque) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _opaque_pthread_rwlock_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 192usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _opaque_pthread_rwlock_t"]
        [::std::mem::size_of::<_opaque_pthread_rwlock_t>() - 200usize];
    ["Alignment of _opaque_pthread_rwlock_t"]
        [::std::mem::align_of::<_opaque_pthread_rwlock_t>() - 8usize];
    ["Offset of field: _opaque_pthread_rwlock_t::__sig"]
        [::std::mem::offset_of!(_opaque_pthread_rwlock_t, __sig) - 0usize];
    ["Offset of field: _opaque_pthread_rwlock_t::__opaque"]
        [::std::mem::offset_of!(_opaque_pthread_rwlock_t, __opaque) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _opaque_pthread_rwlockattr_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 16usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _opaque_pthread_rwlockattr_t"]
        [::std::mem::size_of::<_opaque_pthread_rwlockattr_t>() - 24usize];
    ["Alignment of _opaque_pthread_rwlockattr_t"]
        [::std::mem::align_of::<_opaque_pthread_rwlockattr_t>() - 8usize];
    ["Offset of field: _opaque_pthread_rwlockattr_t::__sig"]
        [::std::mem::offset_of!(_opaque_pthread_rwlockattr_t, __sig) - 0usize];
    ["Offset of field: _opaque_pthread_rwlockattr_t::__opaque"]
        [::std::mem::offset_of!(_opaque_pthread_rwlockattr_t, __opaque) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _opaque_pthread_t {
    pub __sig: ::std::os::raw::c_long,
    pub __cleanup_stack: *mut __darwin_pthread_handler_rec,
    pub __opaque: [::std::os::raw::c_char; 8176usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _opaque_pthread_t"][::std::mem::size_of::<_opaque_pthread_t>() - 8192usize];
    ["Alignment of _opaque_pthread_t"][::std::mem::align_of::<_opaque_pthread_t>() - 8usize];
    ["Offset of field: _opaque_pthread_t::__sig"]
        [::std::mem::offset_of!(_opaque_pthread_t, __sig) - 0usize];
    ["Offset of field: _opaque_pthread_t::__cleanup_stack"]
        [::std::mem::offset_of!(_opaque_pthread_t, __cleanup_stack) - 8usize];
    ["Offset of field: _opaque_pthread_t::__opaque"]
        [::std::mem::offset_of!(_opaque_pthread_t, __opaque) - 16usize];
};
pub type __darwin_pthread_attr_t = _opaque_pthread_attr_t;
pub type __darwin_pthread_cond_t = _opaque_pthread_cond_t;
pub type __darwin_pthread_condattr_t = _opaque_pthread_condattr_t;
pub type __darwin_pthread_key_t = ::std::os::raw::c_ulong;
pub type __darwin_pthread_mutex_t = _opaque_pthread_mutex_t;
pub type __darwin_pthread_mutexattr_t = _opaque_pthread_mutexattr_t;
pub type __darwin_pthread_once_t = _opaque_pthread_once_t;
pub type __darwin_pthread_rwlock_t = _opaque_pthread_rwlock_t;
pub type __darwin_pthread_rwlockattr_t = _opaque_pthread_rwlockattr_t;
pub type __darwin_pthread_t = *mut _opaque_pthread_t;
pub type intmax_t = ::std::os::raw::c_long;
pub type uintmax_t = ::std::os::raw::c_ulong;
pub type std___enable_if_t = u8;
pub type std_enable_if_t = u8;
pub type std_integral_constant_value_type<_Tp> = _Tp;
pub type std_integral_constant_type = u8;
pub type std_true_type = u8;
pub type std_false_type = u8;
pub type std__BoolConstant = u8;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct std_remove_cv {
    pub _address: u8,
}
pub type std_remove_cv_type<_Tp> = _Tp;
pub type std___remove_cv_t<_Tp> = _Tp;
pub type std_remove_cv_t<_Tp> = std___remove_cv_t<_Tp>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct std___libcpp_is_integral {
    pub _address: u8,
}
pub const std___libcpp_is_integral_value: std___libcpp_is_integral__bindgen_ty_1 = 0;
pub type std___libcpp_is_integral__bindgen_ty_1 = i32;
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of template specialization: std___libcpp_is_integral_open0_bool__close0"]
        [::std::mem::size_of::<std___libcpp_is_integral>() - 1usize];
    ["Align of template specialization: std___libcpp_is_integral_open0_bool__close0"]
        [::std::mem::align_of::<std___libcpp_is_integral>() - 1usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of template specialization: std___libcpp_is_integral_open0_char_close0"]
        [::std::mem::size_of::<std___libcpp_is_integral>() - 1usize];
    ["Align of template specialization: std___libcpp_is_integral_open0_char_close0"]
        [::std::mem::align_of::<std___libcpp_is_integral>() - 1usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of template specialization: std___libcpp_is_integral_open0_signed_char_close0"]
        [::std::mem::size_of::<std___libcpp_is_integral>() - 1usize];
    ["Align of template specialization: std___libcpp_is_integral_open0_signed_char_close0"]
        [::std::mem::align_of::<std___libcpp_is_integral>() - 1usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of template specialization: std___libcpp_is_integral_open0_unsigned_char_close0"]
        [::std::mem::size_of::<std___libcpp_is_integral>() - 1usize];
    ["Align of template specialization: std___libcpp_is_integral_open0_unsigned_char_close0"]
        [::std::mem::align_of::<std___libcpp_is_integral>() - 1usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of template specialization: std___libcpp_is_integral_open0_wchar_t_close0"]
        [::std::mem::size_of::<std___libcpp_is_integral>() - 1usize];
    ["Align of template specialization: std___libcpp_is_integral_open0_wchar_t_close0"]
        [::std::mem::align_of::<std___libcpp_is_integral>() - 1usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of template specialization: std___libcpp_is_integral_open0_char16_t_close0"]
        [::std::mem::size_of::<std___libcpp_is_integral>() - 1usize];
    ["Align of template specialization: std___libcpp_is_integral_open0_char16_t_close0"]
        [::std::mem::align_of::<std___libcpp_is_integral>() - 1usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of template specialization: std___libcpp_is_integral_open0_char32_t_close0"]
        [::std::mem::size_of::<std___libcpp_is_integral>() - 1usize];
    ["Align of template specialization: std___libcpp_is_integral_open0_char32_t_close0"]
        [::std::mem::align_of::<std___libcpp_is_integral>() - 1usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of template specialization: std___libcpp_is_integral_open0_short_close0"]
        [::std::mem::size_of::<std___libcpp_is_integral>() - 1usize];
    ["Align of template specialization: std___libcpp_is_integral_open0_short_close0"]
        [::std::mem::align_of::<std___libcpp_is_integral>() - 1usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of template specialization: std___libcpp_is_integral_open0_unsigned_short_close0"]
        [::std::mem::size_of::<std___libcpp_is_integral>() - 1usize];
    ["Align of template specialization: std___libcpp_is_integral_open0_unsigned_short_close0"]
        [::std::mem::align_of::<std___libcpp_is_integral>() - 1usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of template specialization: std___libcpp_is_integral_open0_int_close0"]
        [::std::mem::size_of::<std___libcpp_is_integral>() - 1usize];
    ["Align of template specialization: std___libcpp_is_integral_open0_int_close0"]
        [::std::mem::align_of::<std___libcpp_is_integral>() - 1usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of template specialization: std___libcpp_is_integral_open0_unsigned_int_close0"]
        [::std::mem::size_of::<std___libcpp_is_integral>() - 1usize];
    ["Align of template specialization: std___libcpp_is_integral_open0_unsigned_int_close0"]
        [::std::mem::align_of::<std___libcpp_is_integral>() - 1usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of template specialization: std___libcpp_is_integral_open0_long_close0"]
        [::std::mem::size_of::<std___libcpp_is_integral>() - 1usize];
    ["Align of template specialization: std___libcpp_is_integral_open0_long_close0"]
        [::std::mem::align_of::<std___libcpp_is_integral>() - 1usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of template specialization: std___libcpp_is_integral_open0_unsigned_long_close0"]
        [::std::mem::size_of::<std___libcpp_is_integral>() - 1usize];
    ["Align of template specialization: std___libcpp_is_integral_open0_unsigned_long_close0"]
        [::std::mem::align_of::<std___libcpp_is_integral>() - 1usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of template specialization: std___libcpp_is_integral_open0_long_long_close0"]
        [::std::mem::size_of::<std___libcpp_is_integral>() - 1usize];
    ["Align of template specialization: std___libcpp_is_integral_open0_long_long_close0"]
        [::std::mem::align_of::<std___libcpp_is_integral>() - 1usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of template specialization: std___libcpp_is_integral_open0_unsigned_long_long_close0"]
        [::std::mem::size_of::<std___libcpp_is_integral>() - 1usize];
    ["Align of template specialization: std___libcpp_is_integral_open0_unsigned_long_long_close0"]
        [::std::mem::align_of::<std___libcpp_is_integral>() - 1usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of template specialization: std___libcpp_is_integral_open0___int128_close0"]
        [::std::mem::size_of::<std___libcpp_is_integral>() - 1usize];
    ["Align of template specialization: std___libcpp_is_integral_open0___int128_close0"]
        [::std::mem::align_of::<std___libcpp_is_integral>() - 1usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of template specialization: std___libcpp_is_integral_open0_unsigned___int128_close0"]
        [::std::mem::size_of::<std___libcpp_is_integral>() - 1usize];
    ["Align of template specialization: std___libcpp_is_integral_open0_unsigned___int128_close0"]
        [::std::mem::align_of::<std___libcpp_is_integral>() - 1usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct std_is_integral {
    pub _address: u8,
}
pub type std_nullptr_t = *const ::std::os::raw::c_void;
pub type max_align_t = f64;
pub type nrd_Identifier = u32;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nrd_Instance {
    _unused: [u8; 0],
}
pub const nrd_Result_SUCCESS: nrd_Result = 0;
pub const nrd_Result_FAILURE: nrd_Result = 1;
pub const nrd_Result_INVALID_ARGUMENT: nrd_Result = 2;
pub const nrd_Result_UNSUPPORTED: nrd_Result = 3;
pub const nrd_Result_NON_UNIQUE_IDENTIFIER: nrd_Result = 4;
pub const nrd_Result_MAX_NUM: nrd_Result = 5;
pub type nrd_Result = u32;
pub const nrd_ResourceType_IN_MV: nrd_ResourceType = 0;
pub const nrd_ResourceType_IN_NORMAL_ROUGHNESS: nrd_ResourceType = 1;
pub const nrd_ResourceType_IN_VIEWZ: nrd_ResourceType = 2;
pub const nrd_ResourceType_IN_DIFF_CONFIDENCE: nrd_ResourceType = 3;
pub const nrd_ResourceType_IN_SPEC_CONFIDENCE: nrd_ResourceType = 4;
pub const nrd_ResourceType_IN_DISOCCLUSION_THRESHOLD_MIX: nrd_ResourceType = 5;
pub const nrd_ResourceType_IN_DIFF_RADIANCE_HITDIST: nrd_ResourceType = 6;
pub const nrd_ResourceType_IN_SPEC_RADIANCE_HITDIST: nrd_ResourceType = 7;
pub const nrd_ResourceType_IN_DIFF_HITDIST: nrd_ResourceType = 8;
pub const nrd_ResourceType_IN_SPEC_HITDIST: nrd_ResourceType = 9;
pub const nrd_ResourceType_IN_DIFF_DIRECTION_HITDIST: nrd_ResourceType = 10;
pub const nrd_ResourceType_IN_DIFF_SH0: nrd_ResourceType = 11;
pub const nrd_ResourceType_IN_DIFF_SH1: nrd_ResourceType = 12;
pub const nrd_ResourceType_IN_SPEC_SH0: nrd_ResourceType = 13;
pub const nrd_ResourceType_IN_SPEC_SH1: nrd_ResourceType = 14;
pub const nrd_ResourceType_IN_PENUMBRA: nrd_ResourceType = 15;
pub const nrd_ResourceType_IN_TRANSLUCENCY: nrd_ResourceType = 16;
pub const nrd_ResourceType_IN_SIGNAL: nrd_ResourceType = 17;
pub const nrd_ResourceType_OUT_DIFF_RADIANCE_HITDIST: nrd_ResourceType = 18;
pub const nrd_ResourceType_OUT_SPEC_RADIANCE_HITDIST: nrd_ResourceType = 19;
pub const nrd_ResourceType_OUT_DIFF_SH0: nrd_ResourceType = 20;
pub const nrd_ResourceType_OUT_DIFF_SH1: nrd_ResourceType = 21;
pub const nrd_ResourceType_OUT_SPEC_SH0: nrd_ResourceType = 22;
pub const nrd_ResourceType_OUT_SPEC_SH1: nrd_ResourceType = 23;
pub const nrd_ResourceType_OUT_DIFF_HITDIST: nrd_ResourceType = 24;
pub const nrd_ResourceType_OUT_SPEC_HITDIST: nrd_ResourceType = 25;
pub const nrd_ResourceType_OUT_DIFF_DIRECTION_HITDIST: nrd_ResourceType = 26;
pub const nrd_ResourceType_OUT_SHADOW_TRANSLUCENCY: nrd_ResourceType = 27;
pub const nrd_ResourceType_OUT_SIGNAL: nrd_ResourceType = 28;
pub const nrd_ResourceType_OUT_VALIDATION: nrd_ResourceType = 29;
pub const nrd_ResourceType_TRANSIENT_POOL: nrd_ResourceType = 30;
pub const nrd_ResourceType_PERMANENT_POOL: nrd_ResourceType = 31;
pub const nrd_ResourceType_MAX_NUM: nrd_ResourceType = 32;
pub type nrd_ResourceType = u32;
pub const nrd_Denoiser_REBLUR_DIFFUSE: nrd_Denoiser = 0;
pub const nrd_Denoiser_REBLUR_DIFFUSE_OCCLUSION: nrd_Denoiser = 1;
pub const nrd_Denoiser_REBLUR_DIFFUSE_SH: nrd_Denoiser = 2;
pub const nrd_Denoiser_REBLUR_SPECULAR: nrd_Denoiser = 3;
pub const nrd_Denoiser_REBLUR_SPECULAR_OCCLUSION: nrd_Denoiser = 4;
pub const nrd_Denoiser_REBLUR_SPECULAR_SH: nrd_Denoiser = 5;
pub const nrd_Denoiser_REBLUR_DIFFUSE_SPECULAR: nrd_Denoiser = 6;
pub const nrd_Denoiser_REBLUR_DIFFUSE_SPECULAR_OCCLUSION: nrd_Denoiser = 7;
pub const nrd_Denoiser_REBLUR_DIFFUSE_SPECULAR_SH: nrd_Denoiser = 8;
pub const nrd_Denoiser_REBLUR_DIFFUSE_DIRECTIONAL_OCCLUSION: nrd_Denoiser = 9;
pub const nrd_Denoiser_RELAX_DIFFUSE: nrd_Denoiser = 10;
pub const nrd_Denoiser_RELAX_DIFFUSE_SH: nrd_Denoiser = 11;
pub const nrd_Denoiser_RELAX_SPECULAR: nrd_Denoiser = 12;
pub const nrd_Denoiser_RELAX_SPECULAR_SH: nrd_Denoiser = 13;
pub const nrd_Denoiser_RELAX_DIFFUSE_SPECULAR: nrd_Denoiser = 14;
pub const nrd_Denoiser_RELAX_DIFFUSE_SPECULAR_SH: nrd_Denoiser = 15;
pub const nrd_Denoiser_SIGMA_SHADOW: nrd_Denoiser = 16;
pub const nrd_Denoiser_SIGMA_SHADOW_TRANSLUCENCY: nrd_Denoiser = 17;
pub const nrd_Denoiser_REFERENCE: nrd_Denoiser = 18;
pub const nrd_Denoiser_MAX_NUM: nrd_Denoiser = 19;
pub type nrd_Denoiser = u32;
pub const nrd_Format_R8_UNORM: nrd_Format = 0;
pub const nrd_Format_R8_SNORM: nrd_Format = 1;
pub const nrd_Format_R8_UINT: nrd_Format = 2;
pub const nrd_Format_R8_SINT: nrd_Format = 3;
pub const nrd_Format_RG8_UNORM: nrd_Format = 4;
pub const nrd_Format_RG8_SNORM: nrd_Format = 5;
pub const nrd_Format_RG8_UINT: nrd_Format = 6;
pub const nrd_Format_RG8_SINT: nrd_Format = 7;
pub const nrd_Format_RGBA8_UNORM: nrd_Format = 8;
pub const nrd_Format_RGBA8_SNORM: nrd_Format = 9;
pub const nrd_Format_RGBA8_UINT: nrd_Format = 10;
pub const nrd_Format_RGBA8_SINT: nrd_Format = 11;
pub const nrd_Format_RGBA8_SRGB: nrd_Format = 12;
pub const nrd_Format_R16_UNORM: nrd_Format = 13;
pub const nrd_Format_R16_SNORM: nrd_Format = 14;
pub const nrd_Format_R16_UINT: nrd_Format = 15;
pub const nrd_Format_R16_SINT: nrd_Format = 16;
pub const nrd_Format_R16_SFLOAT: nrd_Format = 17;
pub const nrd_Format_RG16_UNORM: nrd_Format = 18;
pub const nrd_Format_RG16_SNORM: nrd_Format = 19;
pub const nrd_Format_RG16_UINT: nrd_Format = 20;
pub const nrd_Format_RG16_SINT: nrd_Format = 21;
pub const nrd_Format_RG16_SFLOAT: nrd_Format = 22;
pub const nrd_Format_RGBA16_UNORM: nrd_Format = 23;
pub const nrd_Format_RGBA16_SNORM: nrd_Format = 24;
pub const nrd_Format_RGBA16_UINT: nrd_Format = 25;
pub const nrd_Format_RGBA16_SINT: nrd_Format = 26;
pub const nrd_Format_RGBA16_SFLOAT: nrd_Format = 27;
pub const nrd_Format_R32_UINT: nrd_Format = 28;
pub const nrd_Format_R32_SINT: nrd_Format = 29;
pub const nrd_Format_R32_SFLOAT: nrd_Format = 30;
pub const nrd_Format_RG32_UINT: nrd_Format = 31;
pub const nrd_Format_RG32_SINT: nrd_Format = 32;
pub const nrd_Format_RG32_SFLOAT: nrd_Format = 33;
pub const nrd_Format_RGB32_UINT: nrd_Format = 34;
pub const nrd_Format_RGB32_SINT: nrd_Format = 35;
pub const nrd_Format_RGB32_SFLOAT: nrd_Format = 36;
pub const nrd_Format_RGBA32_UINT: nrd_Format = 37;
pub const nrd_Format_RGBA32_SINT: nrd_Format = 38;
pub const nrd_Format_RGBA32_SFLOAT: nrd_Format = 39;
pub const nrd_Format_R10_G10_B10_A2_UNORM: nrd_Format = 40;
pub const nrd_Format_R10_G10_B10_A2_UINT: nrd_Format = 41;
pub const nrd_Format_R11_G11_B10_UFLOAT: nrd_Format = 42;
pub const nrd_Format_R9_G9_B9_E5_UFLOAT: nrd_Format = 43;
pub const nrd_Format_MAX_NUM: nrd_Format = 44;
pub type nrd_Format = u32;
pub const nrd_DescriptorType_TEXTURE: nrd_DescriptorType = 0;
pub const nrd_DescriptorType_STORAGE_TEXTURE: nrd_DescriptorType = 1;
pub const nrd_DescriptorType_MAX_NUM: nrd_DescriptorType = 2;
pub type nrd_DescriptorType = u32;
pub const nrd_Sampler_NEAREST_CLAMP: nrd_Sampler = 0;
pub const nrd_Sampler_LINEAR_CLAMP: nrd_Sampler = 1;
pub const nrd_Sampler_MAX_NUM: nrd_Sampler = 2;
pub type nrd_Sampler = u32;
pub const nrd_NormalEncoding_RGBA8_UNORM: nrd_NormalEncoding = 0;
pub const nrd_NormalEncoding_RGBA8_SNORM: nrd_NormalEncoding = 1;
pub const nrd_NormalEncoding_R10_G10_B10_A2_UNORM: nrd_NormalEncoding = 2;
pub const nrd_NormalEncoding_RGBA16_UNORM: nrd_NormalEncoding = 3;
pub const nrd_NormalEncoding_RGBA16_SNORM: nrd_NormalEncoding = 4;
pub const nrd_NormalEncoding_MAX_NUM: nrd_NormalEncoding = 5;
pub type nrd_NormalEncoding = u8;
pub const nrd_RoughnessEncoding_SQ_LINEAR: nrd_RoughnessEncoding = 0;
pub const nrd_RoughnessEncoding_LINEAR: nrd_RoughnessEncoding = 1;
pub const nrd_RoughnessEncoding_SQRT_LINEAR: nrd_RoughnessEncoding = 2;
pub const nrd_RoughnessEncoding_MAX_NUM: nrd_RoughnessEncoding = 3;
pub type nrd_RoughnessEncoding = u8;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nrd_AllocationCallbacks {
    pub Allocate: ::std::option::Option<
        unsafe extern "C" fn(
            userArg: *mut ::std::os::raw::c_void,
            size: usize,
            alignment: usize,
        ) -> *mut ::std::os::raw::c_void,
    >,
    pub Reallocate: ::std::option::Option<
        unsafe extern "C" fn(
            userArg: *mut ::std::os::raw::c_void,
            memory: *mut ::std::os::raw::c_void,
            size: usize,
            alignment: usize,
        ) -> *mut ::std::os::raw::c_void,
    >,
    pub Free: ::std::option::Option<
        unsafe extern "C" fn(
            userArg: *mut ::std::os::raw::c_void,
            memory: *mut ::std::os::raw::c_void,
        ),
    >,
    pub userArg: *mut ::std::os::raw::c_void,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of nrd_AllocationCallbacks"][::std::mem::size_of::<nrd_AllocationCallbacks>() - 32usize];
    ["Alignment of nrd_AllocationCallbacks"]
        [::std::mem::align_of::<nrd_AllocationCallbacks>() - 8usize];
    ["Offset of field: nrd_AllocationCallbacks::Allocate"]
        [::std::mem::offset_of!(nrd_AllocationCallbacks, Allocate) - 0usize];
    ["Offset of field: nrd_AllocationCallbacks::Reallocate"]
        [::std::mem::offset_of!(nrd_AllocationCallbacks, Reallocate) - 8usize];
    ["Offset of field: nrd_AllocationCallbacks::Free"]
        [::std::mem::offset_of!(nrd_AllocationCallbacks, Free) - 16usize];
    ["Offset of field: nrd_AllocationCallbacks::userArg"]
        [::std::mem::offset_of!(nrd_AllocationCallbacks, userArg) - 24usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nrd_SPIRVBindingOffsets {
    pub samplerOffset: u32,
    pub textureOffset: u32,
    pub constantBufferOffset: u32,
    pub storageTextureAndBufferOffset: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of nrd_SPIRVBindingOffsets"][::std::mem::size_of::<nrd_SPIRVBindingOffsets>() - 16usize];
    ["Alignment of nrd_SPIRVBindingOffsets"]
        [::std::mem::align_of::<nrd_SPIRVBindingOffsets>() - 4usize];
    ["Offset of field: nrd_SPIRVBindingOffsets::samplerOffset"]
        [::std::mem::offset_of!(nrd_SPIRVBindingOffsets, samplerOffset) - 0usize];
    ["Offset of field: nrd_SPIRVBindingOffsets::textureOffset"]
        [::std::mem::offset_of!(nrd_SPIRVBindingOffsets, textureOffset) - 4usize];
    ["Offset of field: nrd_SPIRVBindingOffsets::constantBufferOffset"]
        [::std::mem::offset_of!(nrd_SPIRVBindingOffsets, constantBufferOffset) - 8usize];
    ["Offset of field: nrd_SPIRVBindingOffsets::storageTextureAndBufferOffset"]
        [::std::mem::offset_of!(nrd_SPIRVBindingOffsets, storageTextureAndBufferOffset) - 12usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nrd_LibraryDesc {
    pub spirvBindingOffsets: nrd_SPIRVBindingOffsets,
    pub supportedDenoisers: *const nrd_Denoiser,
    pub supportedDenoisersNum: u32,
    pub versionMajor: u8,
    pub versionMinor: u8,
    pub versionBuild: u8,
    pub normalEncoding: nrd_NormalEncoding,
    pub roughnessEncoding: nrd_RoughnessEncoding,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of nrd_LibraryDesc"][::std::mem::size_of::<nrd_LibraryDesc>() - 40usize];
    ["Alignment of nrd_LibraryDesc"][::std::mem::align_of::<nrd_LibraryDesc>() - 8usize];
    ["Offset of field: nrd_LibraryDesc::spirvBindingOffsets"]
        [::std::mem::offset_of!(nrd_LibraryDesc, spirvBindingOffsets) - 0usize];
    ["Offset of field: nrd_LibraryDesc::supportedDenoisers"]
        [::std::mem::offset_of!(nrd_LibraryDesc, supportedDenoisers) - 16usize];
    ["Offset of field: nrd_LibraryDesc::supportedDenoisersNum"]
        [::std::mem::offset_of!(nrd_LibraryDesc, supportedDenoisersNum) - 24usize];
    ["Offset of field: nrd_LibraryDesc::versionMajor"]
        [::std::mem::offset_of!(nrd_LibraryDesc, versionMajor) - 28usize];
    ["Offset of field: nrd_LibraryDesc::versionMinor"]
        [::std::mem::offset_of!(nrd_LibraryDesc, versionMinor) - 29usize];
    ["Offset of field: nrd_LibraryDesc::versionBuild"]
        [::std::mem::offset_of!(nrd_LibraryDesc, versionBuild) - 30usize];
    ["Offset of field: nrd_LibraryDesc::normalEncoding"]
        [::std::mem::offset_of!(nrd_LibraryDesc, normalEncoding) - 31usize];
    ["Offset of field: nrd_LibraryDesc::roughnessEncoding"]
        [::std::mem::offset_of!(nrd_LibraryDesc, roughnessEncoding) - 32usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nrd_DenoiserDesc {
    pub identifier: nrd_Identifier,
    pub denoiser: nrd_Denoiser,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of nrd_DenoiserDesc"][::std::mem::size_of::<nrd_DenoiserDesc>() - 8usize];
    ["Alignment of nrd_DenoiserDesc"][::std::mem::align_of::<nrd_DenoiserDesc>() - 4usize];
    ["Offset of field: nrd_DenoiserDesc::identifier"]
        [::std::mem::offset_of!(nrd_DenoiserDesc, identifier) - 0usize];
    ["Offset of field: nrd_DenoiserDesc::denoiser"]
        [::std::mem::offset_of!(nrd_DenoiserDesc, denoiser) - 4usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nrd_InstanceCreationDesc {
    pub allocationCallbacks: nrd_AllocationCallbacks,
    pub denoisers: *const nrd_DenoiserDesc,
    pub denoisersNum: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of nrd_InstanceCreationDesc"]
        [::std::mem::size_of::<nrd_InstanceCreationDesc>() - 48usize];
    ["Alignment of nrd_InstanceCreationDesc"]
        [::std::mem::align_of::<nrd_InstanceCreationDesc>() - 8usize];
    ["Offset of field: nrd_InstanceCreationDesc::allocationCallbacks"]
        [::std::mem::offset_of!(nrd_InstanceCreationDesc, allocationCallbacks) - 0usize];
    ["Offset of field: nrd_InstanceCreationDesc::denoisers"]
        [::std::mem::offset_of!(nrd_InstanceCreationDesc, denoisers) - 32usize];
    ["Offset of field: nrd_InstanceCreationDesc::denoisersNum"]
        [::std::mem::offset_of!(nrd_InstanceCreationDesc, denoisersNum) - 40usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nrd_TextureDesc {
    pub format: nrd_Format,
    pub downsampleFactor: u16,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of nrd_TextureDesc"][::std::mem::size_of::<nrd_TextureDesc>() - 8usize];
    ["Alignment of nrd_TextureDesc"][::std::mem::align_of::<nrd_TextureDesc>() - 4usize];
    ["Offset of field: nrd_TextureDesc::format"]
        [::std::mem::offset_of!(nrd_TextureDesc, format) - 0usize];
    ["Offset of field: nrd_TextureDesc::downsampleFactor"]
        [::std::mem::offset_of!(nrd_TextureDesc, downsampleFactor) - 4usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nrd_ResourceDesc {
    pub descriptorType: nrd_DescriptorType,
    pub type_: nrd_ResourceType,
    pub indexInPool: u16,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of nrd_ResourceDesc"][::std::mem::size_of::<nrd_ResourceDesc>() - 12usize];
    ["Alignment of nrd_ResourceDesc"][::std::mem::align_of::<nrd_ResourceDesc>() - 4usize];
    ["Offset of field: nrd_ResourceDesc::descriptorType"]
        [::std::mem::offset_of!(nrd_ResourceDesc, descriptorType) - 0usize];
    ["Offset of field: nrd_ResourceDesc::type_"]
        [::std::mem::offset_of!(nrd_ResourceDesc, type_) - 4usize];
    ["Offset of field: nrd_ResourceDesc::indexInPool"]
        [::std::mem::offset_of!(nrd_ResourceDesc, indexInPool) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nrd_ResourceRangeDesc {
    pub descriptorType: nrd_DescriptorType,
    pub descriptorsNum: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of nrd_ResourceRangeDesc"][::std::mem::size_of::<nrd_ResourceRangeDesc>() - 8usize];
    ["Alignment of nrd_ResourceRangeDesc"]
        [::std::mem::align_of::<nrd_ResourceRangeDesc>() - 4usize];
    ["Offset of field: nrd_ResourceRangeDesc::descriptorType"]
        [::std::mem::offset_of!(nrd_ResourceRangeDesc, descriptorType) - 0usize];
    ["Offset of field: nrd_ResourceRangeDesc::descriptorsNum"]
        [::std::mem::offset_of!(nrd_ResourceRangeDesc, descriptorsNum) - 4usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nrd_ComputeShaderDesc {
    pub bytecode: *const ::std::os::raw::c_void,
    pub size: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of nrd_ComputeShaderDesc"][::std::mem::size_of::<nrd_ComputeShaderDesc>() - 16usize];
    ["Alignment of nrd_ComputeShaderDesc"]
        [::std::mem::align_of::<nrd_ComputeShaderDesc>() - 8usize];
    ["Offset of field: nrd_ComputeShaderDesc::bytecode"]
        [::std::mem::offset_of!(nrd_ComputeShaderDesc, bytecode) - 0usize];
    ["Offset of field: nrd_ComputeShaderDesc::size"]
        [::std::mem::offset_of!(nrd_ComputeShaderDesc, size) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nrd_PipelineDesc {
    pub computeShaderDXBC: nrd_ComputeShaderDesc,
    pub computeShaderDXIL: nrd_ComputeShaderDesc,
    pub computeShaderSPIRV: nrd_ComputeShaderDesc,
    /// Precompiled `.metallib` bytes (see `nrd::PipelineDesc::computeShaderMetal` in NRDDescs.h).
    pub computeShaderMetal: nrd_ComputeShaderDesc,
    pub resourceRanges: *const nrd_ResourceRangeDesc,
    pub resourceRangesNum: u32,
    pub hasConstantData: bool,
    pub shaderIdentifier: [::std::os::raw::c_char; 256usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of nrd_PipelineDesc"][::std::mem::size_of::<nrd_PipelineDesc>() - 336usize];
    ["Alignment of nrd_PipelineDesc"][::std::mem::align_of::<nrd_PipelineDesc>() - 8usize];
    ["Offset of field: nrd_PipelineDesc::computeShaderDXBC"]
        [::std::mem::offset_of!(nrd_PipelineDesc, computeShaderDXBC) - 0usize];
    ["Offset of field: nrd_PipelineDesc::computeShaderDXIL"]
        [::std::mem::offset_of!(nrd_PipelineDesc, computeShaderDXIL) - 16usize];
    ["Offset of field: nrd_PipelineDesc::computeShaderSPIRV"]
        [::std::mem::offset_of!(nrd_PipelineDesc, computeShaderSPIRV) - 32usize];
    ["Offset of field: nrd_PipelineDesc::computeShaderMetal"]
        [::std::mem::offset_of!(nrd_PipelineDesc, computeShaderMetal) - 48usize];
    ["Offset of field: nrd_PipelineDesc::resourceRanges"]
        [::std::mem::offset_of!(nrd_PipelineDesc, resourceRanges) - 64usize];
    ["Offset of field: nrd_PipelineDesc::resourceRangesNum"]
        [::std::mem::offset_of!(nrd_PipelineDesc, resourceRangesNum) - 72usize];
    ["Offset of field: nrd_PipelineDesc::hasConstantData"]
        [::std::mem::offset_of!(nrd_PipelineDesc, hasConstantData) - 76usize];
    ["Offset of field: nrd_PipelineDesc::shaderIdentifier"]
        [::std::mem::offset_of!(nrd_PipelineDesc, shaderIdentifier) - 77usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nrd_DescriptorPoolDesc {
    pub perSetTexturesMaxNum: u32,
    pub perSetStorageTexturesMaxNum: u32,
    pub totalTexturesNum: u32,
    pub totalStorageTexturesNum: u32,
    pub setsMaxNum: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of nrd_DescriptorPoolDesc"][::std::mem::size_of::<nrd_DescriptorPoolDesc>() - 20usize];
    ["Alignment of nrd_DescriptorPoolDesc"]
        [::std::mem::align_of::<nrd_DescriptorPoolDesc>() - 4usize];
    ["Offset of field: nrd_DescriptorPoolDesc::perSetTexturesMaxNum"]
        [::std::mem::offset_of!(nrd_DescriptorPoolDesc, perSetTexturesMaxNum) - 0usize];
    ["Offset of field: nrd_DescriptorPoolDesc::perSetStorageTexturesMaxNum"]
        [::std::mem::offset_of!(nrd_DescriptorPoolDesc, perSetStorageTexturesMaxNum) - 4usize];
    ["Offset of field: nrd_DescriptorPoolDesc::totalTexturesNum"]
        [::std::mem::offset_of!(nrd_DescriptorPoolDesc, totalTexturesNum) - 8usize];
    ["Offset of field: nrd_DescriptorPoolDesc::totalStorageTexturesNum"]
        [::std::mem::offset_of!(nrd_DescriptorPoolDesc, totalStorageTexturesNum) - 12usize];
    ["Offset of field: nrd_DescriptorPoolDesc::setsMaxNum"]
        [::std::mem::offset_of!(nrd_DescriptorPoolDesc, setsMaxNum) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nrd_InstanceDesc {
    pub constantBufferAndSamplersSpaceIndex: u32,
    pub resourcesSpaceIndex: u32,
    pub constantBufferRegisterIndex: u32,
    pub samplersBaseRegisterIndex: u32,
    pub resourcesBaseRegisterIndex: u32,
    pub constantBufferMaxDataSize: u32,
    pub samplers: *const nrd_Sampler,
    pub samplersNum: u32,
    pub shaderEntryPoint: *const ::std::os::raw::c_char,
    pub pipelines: *const nrd_PipelineDesc,
    pub pipelinesNum: u32,
    pub permanentPool: *const nrd_TextureDesc,
    pub permanentPoolSize: u32,
    pub transientPool: *const nrd_TextureDesc,
    pub transientPoolSize: u32,
    pub descriptorPoolDesc: nrd_DescriptorPoolDesc,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of nrd_InstanceDesc"][::std::mem::size_of::<nrd_InstanceDesc>() - 112usize];
    ["Alignment of nrd_InstanceDesc"][::std::mem::align_of::<nrd_InstanceDesc>() - 8usize];
    ["Offset of field: nrd_InstanceDesc::constantBufferAndSamplersSpaceIndex"]
        [::std::mem::offset_of!(nrd_InstanceDesc, constantBufferAndSamplersSpaceIndex) - 0usize];
    ["Offset of field: nrd_InstanceDesc::resourcesSpaceIndex"]
        [::std::mem::offset_of!(nrd_InstanceDesc, resourcesSpaceIndex) - 4usize];
    ["Offset of field: nrd_InstanceDesc::constantBufferRegisterIndex"]
        [::std::mem::offset_of!(nrd_InstanceDesc, constantBufferRegisterIndex) - 8usize];
    ["Offset of field: nrd_InstanceDesc::samplersBaseRegisterIndex"]
        [::std::mem::offset_of!(nrd_InstanceDesc, samplersBaseRegisterIndex) - 12usize];
    ["Offset of field: nrd_InstanceDesc::resourcesBaseRegisterIndex"]
        [::std::mem::offset_of!(nrd_InstanceDesc, resourcesBaseRegisterIndex) - 16usize];
    ["Offset of field: nrd_InstanceDesc::constantBufferMaxDataSize"]
        [::std::mem::offset_of!(nrd_InstanceDesc, constantBufferMaxDataSize) - 20usize];
    ["Offset of field: nrd_InstanceDesc::samplers"]
        [::std::mem::offset_of!(nrd_InstanceDesc, samplers) - 24usize];
    ["Offset of field: nrd_InstanceDesc::samplersNum"]
        [::std::mem::offset_of!(nrd_InstanceDesc, samplersNum) - 32usize];
    ["Offset of field: nrd_InstanceDesc::shaderEntryPoint"]
        [::std::mem::offset_of!(nrd_InstanceDesc, shaderEntryPoint) - 40usize];
    ["Offset of field: nrd_InstanceDesc::pipelines"]
        [::std::mem::offset_of!(nrd_InstanceDesc, pipelines) - 48usize];
    ["Offset of field: nrd_InstanceDesc::pipelinesNum"]
        [::std::mem::offset_of!(nrd_InstanceDesc, pipelinesNum) - 56usize];
    ["Offset of field: nrd_InstanceDesc::permanentPool"]
        [::std::mem::offset_of!(nrd_InstanceDesc, permanentPool) - 64usize];
    ["Offset of field: nrd_InstanceDesc::permanentPoolSize"]
        [::std::mem::offset_of!(nrd_InstanceDesc, permanentPoolSize) - 72usize];
    ["Offset of field: nrd_InstanceDesc::transientPool"]
        [::std::mem::offset_of!(nrd_InstanceDesc, transientPool) - 80usize];
    ["Offset of field: nrd_InstanceDesc::transientPoolSize"]
        [::std::mem::offset_of!(nrd_InstanceDesc, transientPoolSize) - 88usize];
    ["Offset of field: nrd_InstanceDesc::descriptorPoolDesc"]
        [::std::mem::offset_of!(nrd_InstanceDesc, descriptorPoolDesc) - 92usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nrd_DispatchDesc {
    pub name: *const ::std::os::raw::c_char,
    pub identifier: nrd_Identifier,
    pub resources: *const nrd_ResourceDesc,
    pub resourcesNum: u32,
    pub constantBufferData: *const u8,
    pub constantBufferDataSize: u32,
    pub constantBufferDataMatchesPreviousDispatch: bool,
    pub pipelineIndex: u16,
    pub gridWidth: u16,
    pub gridHeight: u16,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of nrd_DispatchDesc"][::std::mem::size_of::<nrd_DispatchDesc>() - 56usize];
    ["Alignment of nrd_DispatchDesc"][::std::mem::align_of::<nrd_DispatchDesc>() - 8usize];
    ["Offset of field: nrd_DispatchDesc::name"]
        [::std::mem::offset_of!(nrd_DispatchDesc, name) - 0usize];
    ["Offset of field: nrd_DispatchDesc::identifier"]
        [::std::mem::offset_of!(nrd_DispatchDesc, identifier) - 8usize];
    ["Offset of field: nrd_DispatchDesc::resources"]
        [::std::mem::offset_of!(nrd_DispatchDesc, resources) - 16usize];
    ["Offset of field: nrd_DispatchDesc::resourcesNum"]
        [::std::mem::offset_of!(nrd_DispatchDesc, resourcesNum) - 24usize];
    ["Offset of field: nrd_DispatchDesc::constantBufferData"]
        [::std::mem::offset_of!(nrd_DispatchDesc, constantBufferData) - 32usize];
    ["Offset of field: nrd_DispatchDesc::constantBufferDataSize"]
        [::std::mem::offset_of!(nrd_DispatchDesc, constantBufferDataSize) - 40usize];
    ["Offset of field: nrd_DispatchDesc::constantBufferDataMatchesPreviousDispatch"][::std::mem::offset_of!(
        nrd_DispatchDesc,
        constantBufferDataMatchesPreviousDispatch
    ) - 44usize];
    ["Offset of field: nrd_DispatchDesc::pipelineIndex"]
        [::std::mem::offset_of!(nrd_DispatchDesc, pipelineIndex) - 46usize];
    ["Offset of field: nrd_DispatchDesc::gridWidth"]
        [::std::mem::offset_of!(nrd_DispatchDesc, gridWidth) - 48usize];
    ["Offset of field: nrd_DispatchDesc::gridHeight"]
        [::std::mem::offset_of!(nrd_DispatchDesc, gridHeight) - 50usize];
};
pub const nrd_CheckerboardMode_OFF: nrd_CheckerboardMode = 0;
pub const nrd_CheckerboardMode_BLACK: nrd_CheckerboardMode = 1;
pub const nrd_CheckerboardMode_WHITE: nrd_CheckerboardMode = 2;
pub const nrd_CheckerboardMode_MAX_NUM: nrd_CheckerboardMode = 3;
pub type nrd_CheckerboardMode = u8;
pub const nrd_AccumulationMode_CONTINUE: nrd_AccumulationMode = 0;
pub const nrd_AccumulationMode_RESTART: nrd_AccumulationMode = 1;
pub const nrd_AccumulationMode_CLEAR_AND_RESTART: nrd_AccumulationMode = 2;
pub const nrd_AccumulationMode_MAX_NUM: nrd_AccumulationMode = 3;
pub type nrd_AccumulationMode = u8;
pub const nrd_HitDistanceReconstructionMode_OFF: nrd_HitDistanceReconstructionMode = 0;
pub const nrd_HitDistanceReconstructionMode_AREA_3X3: nrd_HitDistanceReconstructionMode = 1;
pub const nrd_HitDistanceReconstructionMode_AREA_5X5: nrd_HitDistanceReconstructionMode = 2;
pub const nrd_HitDistanceReconstructionMode_MAX_NUM: nrd_HitDistanceReconstructionMode = 3;
pub type nrd_HitDistanceReconstructionMode = u8;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nrd_CommonSettings {
    pub viewToClipMatrix: [f32; 16usize],
    pub viewToClipMatrixPrev: [f32; 16usize],
    pub worldToViewMatrix: [f32; 16usize],
    pub worldToViewMatrixPrev: [f32; 16usize],
    pub worldPrevToWorldMatrix: [f32; 16usize],
    pub motionVectorScale: [f32; 3usize],
    pub cameraJitter: [f32; 2usize],
    pub cameraJitterPrev: [f32; 2usize],
    pub resourceSize: [u16; 2usize],
    pub resourceSizePrev: [u16; 2usize],
    pub rectSize: [u16; 2usize],
    pub rectSizePrev: [u16; 2usize],
    pub viewZScale: f32,
    pub timeDeltaBetweenFrames: f32,
    pub denoisingRange: f32,
    pub disocclusionThreshold: f32,
    pub disocclusionThresholdAlternate: f32,
    pub cameraAttachedReflectionMaterialID: f32,
    pub strandMaterialID: f32,
    pub historyFixAlternatePixelStrideMaterialID: f32,
    pub strandThickness: f32,
    pub splitScreen: f32,
    pub printfAt: [u16; 2usize],
    pub debug: f32,
    pub rectOrigin: [u32; 2usize],
    pub frameIndex: u32,
    pub accumulationMode: nrd_AccumulationMode,
    pub isMotionVectorInWorldSpace: bool,
    pub isHistoryConfidenceAvailable: bool,
    pub isDisocclusionThresholdMixAvailable: bool,
    pub enableValidation: bool,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of nrd_CommonSettings"][::std::mem::size_of::<nrd_CommonSettings>() - 432usize];
    ["Alignment of nrd_CommonSettings"][::std::mem::align_of::<nrd_CommonSettings>() - 4usize];
    ["Offset of field: nrd_CommonSettings::viewToClipMatrix"]
        [::std::mem::offset_of!(nrd_CommonSettings, viewToClipMatrix) - 0usize];
    ["Offset of field: nrd_CommonSettings::viewToClipMatrixPrev"]
        [::std::mem::offset_of!(nrd_CommonSettings, viewToClipMatrixPrev) - 64usize];
    ["Offset of field: nrd_CommonSettings::worldToViewMatrix"]
        [::std::mem::offset_of!(nrd_CommonSettings, worldToViewMatrix) - 128usize];
    ["Offset of field: nrd_CommonSettings::worldToViewMatrixPrev"]
        [::std::mem::offset_of!(nrd_CommonSettings, worldToViewMatrixPrev) - 192usize];
    ["Offset of field: nrd_CommonSettings::worldPrevToWorldMatrix"]
        [::std::mem::offset_of!(nrd_CommonSettings, worldPrevToWorldMatrix) - 256usize];
    ["Offset of field: nrd_CommonSettings::motionVectorScale"]
        [::std::mem::offset_of!(nrd_CommonSettings, motionVectorScale) - 320usize];
    ["Offset of field: nrd_CommonSettings::cameraJitter"]
        [::std::mem::offset_of!(nrd_CommonSettings, cameraJitter) - 332usize];
    ["Offset of field: nrd_CommonSettings::cameraJitterPrev"]
        [::std::mem::offset_of!(nrd_CommonSettings, cameraJitterPrev) - 340usize];
    ["Offset of field: nrd_CommonSettings::resourceSize"]
        [::std::mem::offset_of!(nrd_CommonSettings, resourceSize) - 348usize];
    ["Offset of field: nrd_CommonSettings::resourceSizePrev"]
        [::std::mem::offset_of!(nrd_CommonSettings, resourceSizePrev) - 352usize];
    ["Offset of field: nrd_CommonSettings::rectSize"]
        [::std::mem::offset_of!(nrd_CommonSettings, rectSize) - 356usize];
    ["Offset of field: nrd_CommonSettings::rectSizePrev"]
        [::std::mem::offset_of!(nrd_CommonSettings, rectSizePrev) - 360usize];
    ["Offset of field: nrd_CommonSettings::viewZScale"]
        [::std::mem::offset_of!(nrd_CommonSettings, viewZScale) - 364usize];
    ["Offset of field: nrd_CommonSettings::timeDeltaBetweenFrames"]
        [::std::mem::offset_of!(nrd_CommonSettings, timeDeltaBetweenFrames) - 368usize];
    ["Offset of field: nrd_CommonSettings::denoisingRange"]
        [::std::mem::offset_of!(nrd_CommonSettings, denoisingRange) - 372usize];
    ["Offset of field: nrd_CommonSettings::disocclusionThreshold"]
        [::std::mem::offset_of!(nrd_CommonSettings, disocclusionThreshold) - 376usize];
    ["Offset of field: nrd_CommonSettings::disocclusionThresholdAlternate"]
        [::std::mem::offset_of!(nrd_CommonSettings, disocclusionThresholdAlternate) - 380usize];
    ["Offset of field: nrd_CommonSettings::cameraAttachedReflectionMaterialID"]
        [::std::mem::offset_of!(nrd_CommonSettings, cameraAttachedReflectionMaterialID) - 384usize];
    ["Offset of field: nrd_CommonSettings::strandMaterialID"]
        [::std::mem::offset_of!(nrd_CommonSettings, strandMaterialID) - 388usize];
    ["Offset of field: nrd_CommonSettings::historyFixAlternatePixelStrideMaterialID"][::std::mem::offset_of!(
        nrd_CommonSettings,
        historyFixAlternatePixelStrideMaterialID
    ) - 392usize];
    ["Offset of field: nrd_CommonSettings::strandThickness"]
        [::std::mem::offset_of!(nrd_CommonSettings, strandThickness) - 396usize];
    ["Offset of field: nrd_CommonSettings::splitScreen"]
        [::std::mem::offset_of!(nrd_CommonSettings, splitScreen) - 400usize];
    ["Offset of field: nrd_CommonSettings::printfAt"]
        [::std::mem::offset_of!(nrd_CommonSettings, printfAt) - 404usize];
    ["Offset of field: nrd_CommonSettings::debug"]
        [::std::mem::offset_of!(nrd_CommonSettings, debug) - 408usize];
    ["Offset of field: nrd_CommonSettings::rectOrigin"]
        [::std::mem::offset_of!(nrd_CommonSettings, rectOrigin) - 412usize];
    ["Offset of field: nrd_CommonSettings::frameIndex"]
        [::std::mem::offset_of!(nrd_CommonSettings, frameIndex) - 420usize];
    ["Offset of field: nrd_CommonSettings::accumulationMode"]
        [::std::mem::offset_of!(nrd_CommonSettings, accumulationMode) - 424usize];
    ["Offset of field: nrd_CommonSettings::isMotionVectorInWorldSpace"]
        [::std::mem::offset_of!(nrd_CommonSettings, isMotionVectorInWorldSpace) - 425usize];
    ["Offset of field: nrd_CommonSettings::isHistoryConfidenceAvailable"]
        [::std::mem::offset_of!(nrd_CommonSettings, isHistoryConfidenceAvailable) - 426usize];
    ["Offset of field: nrd_CommonSettings::isDisocclusionThresholdMixAvailable"][::std::mem::offset_of!(
        nrd_CommonSettings,
        isDisocclusionThresholdMixAvailable
    ) - 427usize];
    ["Offset of field: nrd_CommonSettings::enableValidation"]
        [::std::mem::offset_of!(nrd_CommonSettings, enableValidation) - 428usize];
};
pub const nrd_REBLUR_MAX_HISTORY_FRAME_NUM: u32 = 63;
pub const nrd_REBLUR_DEFAULT_ACCUMULATION_TIME: f32 = 0.5;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nrd_ReblurHitDistanceParameters {
    pub A: f32,
    pub B: f32,
    pub C: f32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of nrd_ReblurHitDistanceParameters"]
        [::std::mem::size_of::<nrd_ReblurHitDistanceParameters>() - 12usize];
    ["Alignment of nrd_ReblurHitDistanceParameters"]
        [::std::mem::align_of::<nrd_ReblurHitDistanceParameters>() - 4usize];
    ["Offset of field: nrd_ReblurHitDistanceParameters::A"]
        [::std::mem::offset_of!(nrd_ReblurHitDistanceParameters, A) - 0usize];
    ["Offset of field: nrd_ReblurHitDistanceParameters::B"]
        [::std::mem::offset_of!(nrd_ReblurHitDistanceParameters, B) - 4usize];
    ["Offset of field: nrd_ReblurHitDistanceParameters::C"]
        [::std::mem::offset_of!(nrd_ReblurHitDistanceParameters, C) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nrd_ReblurAntilagSettings {
    pub luminanceSigmaScale: f32,
    pub luminanceSensitivity: f32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of nrd_ReblurAntilagSettings"]
        [::std::mem::size_of::<nrd_ReblurAntilagSettings>() - 8usize];
    ["Alignment of nrd_ReblurAntilagSettings"]
        [::std::mem::align_of::<nrd_ReblurAntilagSettings>() - 4usize];
    ["Offset of field: nrd_ReblurAntilagSettings::luminanceSigmaScale"]
        [::std::mem::offset_of!(nrd_ReblurAntilagSettings, luminanceSigmaScale) - 0usize];
    ["Offset of field: nrd_ReblurAntilagSettings::luminanceSensitivity"]
        [::std::mem::offset_of!(nrd_ReblurAntilagSettings, luminanceSensitivity) - 4usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nrd_ReblurResponsiveAccumulationSettings {
    pub roughnessThreshold: f32,
    pub minAccumulatedFrameNum: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of nrd_ReblurResponsiveAccumulationSettings"]
        [::std::mem::size_of::<nrd_ReblurResponsiveAccumulationSettings>() - 8usize];
    ["Alignment of nrd_ReblurResponsiveAccumulationSettings"]
        [::std::mem::align_of::<nrd_ReblurResponsiveAccumulationSettings>() - 4usize];
    ["Offset of field: nrd_ReblurResponsiveAccumulationSettings::roughnessThreshold"][::std::mem::offset_of!(
        nrd_ReblurResponsiveAccumulationSettings,
        roughnessThreshold
    ) - 0usize];
    ["Offset of field: nrd_ReblurResponsiveAccumulationSettings::minAccumulatedFrameNum"][::std::mem::offset_of!(
        nrd_ReblurResponsiveAccumulationSettings,
        minAccumulatedFrameNum
    )
        - 4usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nrd_ReblurConvergenceSettings {
    pub s: f32,
    pub b: f32,
    pub p: f32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of nrd_ReblurConvergenceSettings"]
        [::std::mem::size_of::<nrd_ReblurConvergenceSettings>() - 12usize];
    ["Alignment of nrd_ReblurConvergenceSettings"]
        [::std::mem::align_of::<nrd_ReblurConvergenceSettings>() - 4usize];
    ["Offset of field: nrd_ReblurConvergenceSettings::s"]
        [::std::mem::offset_of!(nrd_ReblurConvergenceSettings, s) - 0usize];
    ["Offset of field: nrd_ReblurConvergenceSettings::b"]
        [::std::mem::offset_of!(nrd_ReblurConvergenceSettings, b) - 4usize];
    ["Offset of field: nrd_ReblurConvergenceSettings::p"]
        [::std::mem::offset_of!(nrd_ReblurConvergenceSettings, p) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nrd_ReblurSettings {
    pub hitDistanceParameters: nrd_ReblurHitDistanceParameters,
    pub antilagSettings: nrd_ReblurAntilagSettings,
    pub responsiveAccumulationSettings: nrd_ReblurResponsiveAccumulationSettings,
    pub convergenceSettings: nrd_ReblurConvergenceSettings,
    pub maxAccumulatedFrameNum: u32,
    pub maxFastAccumulatedFrameNum: u32,
    pub maxStabilizedFrameNum: u32,
    pub historyFixFrameNum: u32,
    pub historyFixBasePixelStride: u32,
    pub historyFixAlternatePixelStride: u32,
    pub fastHistoryClampingSigmaScale: f32,
    pub diffusePrepassBlurRadius: f32,
    pub specularPrepassBlurRadius: f32,
    pub minHitDistanceWeight: f32,
    pub minBlurRadius: f32,
    pub maxBlurRadius: f32,
    pub lobeAngleFraction: f32,
    pub roughnessFraction: f32,
    pub planeDistanceSensitivity: f32,
    pub specularProbabilityThresholdsForMvModification: [f32; 2usize],
    pub fireflySuppressorMinRelativeScale: f32,
    pub minMaterialForDiffuse: f32,
    pub minMaterialForSpecular: f32,
    pub checkerboardMode: nrd_CheckerboardMode,
    pub hitDistanceReconstructionMode: nrd_HitDistanceReconstructionMode,
    pub enableAntiFirefly: bool,
    pub usePrepassOnlyForSpecularMotionEstimation: bool,
    pub returnHistoryLengthInsteadOfOcclusion: bool,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of nrd_ReblurSettings"][::std::mem::size_of::<nrd_ReblurSettings>() - 128usize];
    ["Alignment of nrd_ReblurSettings"][::std::mem::align_of::<nrd_ReblurSettings>() - 4usize];
    ["Offset of field: nrd_ReblurSettings::hitDistanceParameters"]
        [::std::mem::offset_of!(nrd_ReblurSettings, hitDistanceParameters) - 0usize];
    ["Offset of field: nrd_ReblurSettings::antilagSettings"]
        [::std::mem::offset_of!(nrd_ReblurSettings, antilagSettings) - 12usize];
    ["Offset of field: nrd_ReblurSettings::responsiveAccumulationSettings"]
        [::std::mem::offset_of!(nrd_ReblurSettings, responsiveAccumulationSettings) - 20usize];
    ["Offset of field: nrd_ReblurSettings::convergenceSettings"]
        [::std::mem::offset_of!(nrd_ReblurSettings, convergenceSettings) - 28usize];
    ["Offset of field: nrd_ReblurSettings::maxAccumulatedFrameNum"]
        [::std::mem::offset_of!(nrd_ReblurSettings, maxAccumulatedFrameNum) - 40usize];
    ["Offset of field: nrd_ReblurSettings::maxFastAccumulatedFrameNum"]
        [::std::mem::offset_of!(nrd_ReblurSettings, maxFastAccumulatedFrameNum) - 44usize];
    ["Offset of field: nrd_ReblurSettings::maxStabilizedFrameNum"]
        [::std::mem::offset_of!(nrd_ReblurSettings, maxStabilizedFrameNum) - 48usize];
    ["Offset of field: nrd_ReblurSettings::historyFixFrameNum"]
        [::std::mem::offset_of!(nrd_ReblurSettings, historyFixFrameNum) - 52usize];
    ["Offset of field: nrd_ReblurSettings::historyFixBasePixelStride"]
        [::std::mem::offset_of!(nrd_ReblurSettings, historyFixBasePixelStride) - 56usize];
    ["Offset of field: nrd_ReblurSettings::historyFixAlternatePixelStride"]
        [::std::mem::offset_of!(nrd_ReblurSettings, historyFixAlternatePixelStride) - 60usize];
    ["Offset of field: nrd_ReblurSettings::fastHistoryClampingSigmaScale"]
        [::std::mem::offset_of!(nrd_ReblurSettings, fastHistoryClampingSigmaScale) - 64usize];
    ["Offset of field: nrd_ReblurSettings::diffusePrepassBlurRadius"]
        [::std::mem::offset_of!(nrd_ReblurSettings, diffusePrepassBlurRadius) - 68usize];
    ["Offset of field: nrd_ReblurSettings::specularPrepassBlurRadius"]
        [::std::mem::offset_of!(nrd_ReblurSettings, specularPrepassBlurRadius) - 72usize];
    ["Offset of field: nrd_ReblurSettings::minHitDistanceWeight"]
        [::std::mem::offset_of!(nrd_ReblurSettings, minHitDistanceWeight) - 76usize];
    ["Offset of field: nrd_ReblurSettings::minBlurRadius"]
        [::std::mem::offset_of!(nrd_ReblurSettings, minBlurRadius) - 80usize];
    ["Offset of field: nrd_ReblurSettings::maxBlurRadius"]
        [::std::mem::offset_of!(nrd_ReblurSettings, maxBlurRadius) - 84usize];
    ["Offset of field: nrd_ReblurSettings::lobeAngleFraction"]
        [::std::mem::offset_of!(nrd_ReblurSettings, lobeAngleFraction) - 88usize];
    ["Offset of field: nrd_ReblurSettings::roughnessFraction"]
        [::std::mem::offset_of!(nrd_ReblurSettings, roughnessFraction) - 92usize];
    ["Offset of field: nrd_ReblurSettings::planeDistanceSensitivity"]
        [::std::mem::offset_of!(nrd_ReblurSettings, planeDistanceSensitivity) - 96usize];
    ["Offset of field: nrd_ReblurSettings::specularProbabilityThresholdsForMvModification"][::std::mem::offset_of!(
        nrd_ReblurSettings,
        specularProbabilityThresholdsForMvModification
    )
        - 100usize];
    ["Offset of field: nrd_ReblurSettings::fireflySuppressorMinRelativeScale"]
        [::std::mem::offset_of!(nrd_ReblurSettings, fireflySuppressorMinRelativeScale) - 108usize];
    ["Offset of field: nrd_ReblurSettings::minMaterialForDiffuse"]
        [::std::mem::offset_of!(nrd_ReblurSettings, minMaterialForDiffuse) - 112usize];
    ["Offset of field: nrd_ReblurSettings::minMaterialForSpecular"]
        [::std::mem::offset_of!(nrd_ReblurSettings, minMaterialForSpecular) - 116usize];
    ["Offset of field: nrd_ReblurSettings::checkerboardMode"]
        [::std::mem::offset_of!(nrd_ReblurSettings, checkerboardMode) - 120usize];
    ["Offset of field: nrd_ReblurSettings::hitDistanceReconstructionMode"]
        [::std::mem::offset_of!(nrd_ReblurSettings, hitDistanceReconstructionMode) - 121usize];
    ["Offset of field: nrd_ReblurSettings::enableAntiFirefly"]
        [::std::mem::offset_of!(nrd_ReblurSettings, enableAntiFirefly) - 122usize];
    ["Offset of field: nrd_ReblurSettings::usePrepassOnlyForSpecularMotionEstimation"][::std::mem::offset_of!(
        nrd_ReblurSettings,
        usePrepassOnlyForSpecularMotionEstimation
    )
        - 123usize];
    ["Offset of field: nrd_ReblurSettings::returnHistoryLengthInsteadOfOcclusion"][::std::mem::offset_of!(
        nrd_ReblurSettings,
        returnHistoryLengthInsteadOfOcclusion
    ) - 124usize];
};
pub const nrd_RELAX_MAX_HISTORY_FRAME_NUM: u32 = 255;
pub const nrd_RELAX_DEFAULT_ACCUMULATION_TIME: f32 = 0.5;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nrd_RelaxAntilagSettings {
    pub accelerationAmount: f32,
    pub spatialSigmaScale: f32,
    pub temporalSigmaScale: f32,
    pub resetAmount: f32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of nrd_RelaxAntilagSettings"]
        [::std::mem::size_of::<nrd_RelaxAntilagSettings>() - 16usize];
    ["Alignment of nrd_RelaxAntilagSettings"]
        [::std::mem::align_of::<nrd_RelaxAntilagSettings>() - 4usize];
    ["Offset of field: nrd_RelaxAntilagSettings::accelerationAmount"]
        [::std::mem::offset_of!(nrd_RelaxAntilagSettings, accelerationAmount) - 0usize];
    ["Offset of field: nrd_RelaxAntilagSettings::spatialSigmaScale"]
        [::std::mem::offset_of!(nrd_RelaxAntilagSettings, spatialSigmaScale) - 4usize];
    ["Offset of field: nrd_RelaxAntilagSettings::temporalSigmaScale"]
        [::std::mem::offset_of!(nrd_RelaxAntilagSettings, temporalSigmaScale) - 8usize];
    ["Offset of field: nrd_RelaxAntilagSettings::resetAmount"]
        [::std::mem::offset_of!(nrd_RelaxAntilagSettings, resetAmount) - 12usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nrd_RelaxSettings {
    pub antilagSettings: nrd_RelaxAntilagSettings,
    pub diffuseMaxAccumulatedFrameNum: u32,
    pub specularMaxAccumulatedFrameNum: u32,
    pub diffuseMaxFastAccumulatedFrameNum: u32,
    pub specularMaxFastAccumulatedFrameNum: u32,
    pub historyFixFrameNum: u32,
    pub historyFixBasePixelStride: u32,
    pub historyFixAlternatePixelStride: u32,
    pub historyFixEdgeStoppingNormalPower: f32,
    pub fastHistoryClampingSigmaScale: f32,
    pub diffusePrepassBlurRadius: f32,
    pub specularPrepassBlurRadius: f32,
    pub minHitDistanceWeight: f32,
    pub spatialVarianceEstimationHistoryThreshold: u32,
    pub diffusePhiLuminance: f32,
    pub specularPhiLuminance: f32,
    pub lobeAngleFraction: f32,
    pub roughnessFraction: f32,
    pub specularVarianceBoost: f32,
    pub specularLobeAngleSlack: f32,
    pub atrousIterationNum: u32,
    pub diffuseMinLuminanceWeight: f32,
    pub specularMinLuminanceWeight: f32,
    pub depthThreshold: f32,
    pub confidenceDrivenRelaxationMultiplier: f32,
    pub confidenceDrivenLuminanceEdgeStoppingRelaxation: f32,
    pub confidenceDrivenNormalEdgeStoppingRelaxation: f32,
    pub luminanceEdgeStoppingRelaxation: f32,
    pub normalEdgeStoppingRelaxation: f32,
    pub roughnessEdgeStoppingRelaxation: f32,
    pub checkerboardMode: nrd_CheckerboardMode,
    pub hitDistanceReconstructionMode: nrd_HitDistanceReconstructionMode,
    pub minMaterialForDiffuse: f32,
    pub minMaterialForSpecular: f32,
    pub enableAntiFirefly: bool,
    pub enableRoughnessEdgeStopping: bool,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of nrd_RelaxSettings"][::std::mem::size_of::<nrd_RelaxSettings>() - 148usize];
    ["Alignment of nrd_RelaxSettings"][::std::mem::align_of::<nrd_RelaxSettings>() - 4usize];
    ["Offset of field: nrd_RelaxSettings::antilagSettings"]
        [::std::mem::offset_of!(nrd_RelaxSettings, antilagSettings) - 0usize];
    ["Offset of field: nrd_RelaxSettings::diffuseMaxAccumulatedFrameNum"]
        [::std::mem::offset_of!(nrd_RelaxSettings, diffuseMaxAccumulatedFrameNum) - 16usize];
    ["Offset of field: nrd_RelaxSettings::specularMaxAccumulatedFrameNum"]
        [::std::mem::offset_of!(nrd_RelaxSettings, specularMaxAccumulatedFrameNum) - 20usize];
    ["Offset of field: nrd_RelaxSettings::diffuseMaxFastAccumulatedFrameNum"]
        [::std::mem::offset_of!(nrd_RelaxSettings, diffuseMaxFastAccumulatedFrameNum) - 24usize];
    ["Offset of field: nrd_RelaxSettings::specularMaxFastAccumulatedFrameNum"]
        [::std::mem::offset_of!(nrd_RelaxSettings, specularMaxFastAccumulatedFrameNum) - 28usize];
    ["Offset of field: nrd_RelaxSettings::historyFixFrameNum"]
        [::std::mem::offset_of!(nrd_RelaxSettings, historyFixFrameNum) - 32usize];
    ["Offset of field: nrd_RelaxSettings::historyFixBasePixelStride"]
        [::std::mem::offset_of!(nrd_RelaxSettings, historyFixBasePixelStride) - 36usize];
    ["Offset of field: nrd_RelaxSettings::historyFixAlternatePixelStride"]
        [::std::mem::offset_of!(nrd_RelaxSettings, historyFixAlternatePixelStride) - 40usize];
    ["Offset of field: nrd_RelaxSettings::historyFixEdgeStoppingNormalPower"]
        [::std::mem::offset_of!(nrd_RelaxSettings, historyFixEdgeStoppingNormalPower) - 44usize];
    ["Offset of field: nrd_RelaxSettings::fastHistoryClampingSigmaScale"]
        [::std::mem::offset_of!(nrd_RelaxSettings, fastHistoryClampingSigmaScale) - 48usize];
    ["Offset of field: nrd_RelaxSettings::diffusePrepassBlurRadius"]
        [::std::mem::offset_of!(nrd_RelaxSettings, diffusePrepassBlurRadius) - 52usize];
    ["Offset of field: nrd_RelaxSettings::specularPrepassBlurRadius"]
        [::std::mem::offset_of!(nrd_RelaxSettings, specularPrepassBlurRadius) - 56usize];
    ["Offset of field: nrd_RelaxSettings::minHitDistanceWeight"]
        [::std::mem::offset_of!(nrd_RelaxSettings, minHitDistanceWeight) - 60usize];
    ["Offset of field: nrd_RelaxSettings::spatialVarianceEstimationHistoryThreshold"][::std::mem::offset_of!(
        nrd_RelaxSettings,
        spatialVarianceEstimationHistoryThreshold
    ) - 64usize];
    ["Offset of field: nrd_RelaxSettings::diffusePhiLuminance"]
        [::std::mem::offset_of!(nrd_RelaxSettings, diffusePhiLuminance) - 68usize];
    ["Offset of field: nrd_RelaxSettings::specularPhiLuminance"]
        [::std::mem::offset_of!(nrd_RelaxSettings, specularPhiLuminance) - 72usize];
    ["Offset of field: nrd_RelaxSettings::lobeAngleFraction"]
        [::std::mem::offset_of!(nrd_RelaxSettings, lobeAngleFraction) - 76usize];
    ["Offset of field: nrd_RelaxSettings::roughnessFraction"]
        [::std::mem::offset_of!(nrd_RelaxSettings, roughnessFraction) - 80usize];
    ["Offset of field: nrd_RelaxSettings::specularVarianceBoost"]
        [::std::mem::offset_of!(nrd_RelaxSettings, specularVarianceBoost) - 84usize];
    ["Offset of field: nrd_RelaxSettings::specularLobeAngleSlack"]
        [::std::mem::offset_of!(nrd_RelaxSettings, specularLobeAngleSlack) - 88usize];
    ["Offset of field: nrd_RelaxSettings::atrousIterationNum"]
        [::std::mem::offset_of!(nrd_RelaxSettings, atrousIterationNum) - 92usize];
    ["Offset of field: nrd_RelaxSettings::diffuseMinLuminanceWeight"]
        [::std::mem::offset_of!(nrd_RelaxSettings, diffuseMinLuminanceWeight) - 96usize];
    ["Offset of field: nrd_RelaxSettings::specularMinLuminanceWeight"]
        [::std::mem::offset_of!(nrd_RelaxSettings, specularMinLuminanceWeight) - 100usize];
    ["Offset of field: nrd_RelaxSettings::depthThreshold"]
        [::std::mem::offset_of!(nrd_RelaxSettings, depthThreshold) - 104usize];
    ["Offset of field: nrd_RelaxSettings::confidenceDrivenRelaxationMultiplier"][::std::mem::offset_of!(
        nrd_RelaxSettings,
        confidenceDrivenRelaxationMultiplier
    ) - 108usize];
    ["Offset of field: nrd_RelaxSettings::confidenceDrivenLuminanceEdgeStoppingRelaxation"][::std::mem::offset_of!(
        nrd_RelaxSettings,
        confidenceDrivenLuminanceEdgeStoppingRelaxation
    )
        - 112usize];
    ["Offset of field: nrd_RelaxSettings::confidenceDrivenNormalEdgeStoppingRelaxation"][::std::mem::offset_of!(
        nrd_RelaxSettings,
        confidenceDrivenNormalEdgeStoppingRelaxation
    )
        - 116usize];
    ["Offset of field: nrd_RelaxSettings::luminanceEdgeStoppingRelaxation"]
        [::std::mem::offset_of!(nrd_RelaxSettings, luminanceEdgeStoppingRelaxation) - 120usize];
    ["Offset of field: nrd_RelaxSettings::normalEdgeStoppingRelaxation"]
        [::std::mem::offset_of!(nrd_RelaxSettings, normalEdgeStoppingRelaxation) - 124usize];
    ["Offset of field: nrd_RelaxSettings::roughnessEdgeStoppingRelaxation"]
        [::std::mem::offset_of!(nrd_RelaxSettings, roughnessEdgeStoppingRelaxation) - 128usize];
    ["Offset of field: nrd_RelaxSettings::checkerboardMode"]
        [::std::mem::offset_of!(nrd_RelaxSettings, checkerboardMode) - 132usize];
    ["Offset of field: nrd_RelaxSettings::hitDistanceReconstructionMode"]
        [::std::mem::offset_of!(nrd_RelaxSettings, hitDistanceReconstructionMode) - 133usize];
    ["Offset of field: nrd_RelaxSettings::minMaterialForDiffuse"]
        [::std::mem::offset_of!(nrd_RelaxSettings, minMaterialForDiffuse) - 136usize];
    ["Offset of field: nrd_RelaxSettings::minMaterialForSpecular"]
        [::std::mem::offset_of!(nrd_RelaxSettings, minMaterialForSpecular) - 140usize];
    ["Offset of field: nrd_RelaxSettings::enableAntiFirefly"]
        [::std::mem::offset_of!(nrd_RelaxSettings, enableAntiFirefly) - 144usize];
    ["Offset of field: nrd_RelaxSettings::enableRoughnessEdgeStopping"]
        [::std::mem::offset_of!(nrd_RelaxSettings, enableRoughnessEdgeStopping) - 145usize];
};
pub const nrd_SIGMA_MAX_HISTORY_FRAME_NUM: u32 = 7;
pub const nrd_SIGMA_DEFAULT_ACCUMULATION_TIME: f32 = 0.08399999886751175;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nrd_SigmaSettings {
    pub lightDirection: [f32; 3usize],
    pub planeDistanceSensitivity: f32,
    pub maxStabilizedFrameNum: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of nrd_SigmaSettings"][::std::mem::size_of::<nrd_SigmaSettings>() - 20usize];
    ["Alignment of nrd_SigmaSettings"][::std::mem::align_of::<nrd_SigmaSettings>() - 4usize];
    ["Offset of field: nrd_SigmaSettings::lightDirection"]
        [::std::mem::offset_of!(nrd_SigmaSettings, lightDirection) - 0usize];
    ["Offset of field: nrd_SigmaSettings::planeDistanceSensitivity"]
        [::std::mem::offset_of!(nrd_SigmaSettings, planeDistanceSensitivity) - 12usize];
    ["Offset of field: nrd_SigmaSettings::maxStabilizedFrameNum"]
        [::std::mem::offset_of!(nrd_SigmaSettings, maxStabilizedFrameNum) - 16usize];
};
pub const nrd_REFERENCE_MAX_HISTORY_FRAME_NUM: u32 = 4095;
pub const nrd_REFERENCE_DEFAULT_ACCUMULATION_TIME: f32 = 2.0;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nrd_ReferenceSettings {
    pub maxAccumulatedFrameNum: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of nrd_ReferenceSettings"][::std::mem::size_of::<nrd_ReferenceSettings>() - 4usize];
    ["Alignment of nrd_ReferenceSettings"]
        [::std::mem::align_of::<nrd_ReferenceSettings>() - 4usize];
    ["Offset of field: nrd_ReferenceSettings::maxAccumulatedFrameNum"]
        [::std::mem::offset_of!(nrd_ReferenceSettings, maxAccumulatedFrameNum) - 0usize];
};
unsafe extern "C" {
    #[link_name = "\u{1}_CreateInstance"]
    pub fn nrd_CreateInstance(
        instanceCreationDesc: *const nrd_InstanceCreationDesc,
        instance: *mut *mut nrd_Instance,
    ) -> nrd_Result;
}
unsafe extern "C" {
    #[link_name = "\u{1}_DestroyInstance"]
    pub fn nrd_DestroyInstance(instance: *mut nrd_Instance);
}
unsafe extern "C" {
    #[link_name = "\u{1}_GetLibraryDesc"]
    pub fn nrd_GetLibraryDesc() -> *const nrd_LibraryDesc;
}
unsafe extern "C" {
    #[link_name = "\u{1}_GetInstanceDesc"]
    pub fn nrd_GetInstanceDesc(instance: *const nrd_Instance) -> *const nrd_InstanceDesc;
}
unsafe extern "C" {
    #[link_name = "\u{1}_SetCommonSettings"]
    pub fn nrd_SetCommonSettings(
        instance: *mut nrd_Instance,
        commonSettings: *const nrd_CommonSettings,
    ) -> nrd_Result;
}
unsafe extern "C" {
    #[link_name = "\u{1}_SetDenoiserSettings"]
    pub fn nrd_SetDenoiserSettings(
        instance: *mut nrd_Instance,
        identifier: nrd_Identifier,
        denoiserSettings: *const ::std::os::raw::c_void,
    ) -> nrd_Result;
}
unsafe extern "C" {
    #[link_name = "\u{1}_GetComputeDispatches"]
    pub fn nrd_GetComputeDispatches(
        instance: *mut nrd_Instance,
        identifiers: *const nrd_Identifier,
        identifiersNum: u32,
        dispatchDescs: *mut *const nrd_DispatchDesc,
        dispatchDescsNum: *mut u32,
    ) -> nrd_Result;
}
unsafe extern "C" {
    #[link_name = "\u{1}_GetResourceTypeString"]
    pub fn nrd_GetResourceTypeString(
        resourceType: nrd_ResourceType,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    #[link_name = "\u{1}_GetDenoiserString"]
    pub fn nrd_GetDenoiserString(denoiser: nrd_Denoiser) -> *const ::std::os::raw::c_char;
}
pub type __builtin_va_list = *mut ::std::os::raw::c_char;
